/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Search.java
 *
 * Created on 23/06/2009, 23:58:07
 */

package UI;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.Calendar;



/**
 *
 * @author motiab
 */
public class Search extends javax.swing.JFrame {
	private EnterPage _CurEnter;
	private TUI _curTUI;
	private  int _searchMode=0;
	/** Creates new form Search */
	public Search(TUI mytui,EnterPage page ) {
		initComponents();
		this._CurEnter=page;
		this._curTUI=mytui;
		this.to.setVisible(false);
		this.jTextField1.setVisible(false);

	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		conetnt = new javax.swing.JCheckBox();
		author = new javax.swing.JCheckBox();
		date = new javax.swing.JCheckBox();
		jTextField1 = new javax.swing.JTextField();
		key = new javax.swing.JLabel();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		jTextField2 = new javax.swing.JTextField();
		to = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jLabel1.setFont(new java.awt.Font("David", 1, 24));
		jLabel1.setText("Please choose one search option:");

		conetnt.setText("search by content!");
		conetnt.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				conetntMouseClicked(evt);
			}
		});
		conetnt.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				conetntActionPerformed(evt);
			}
		});

		author.setText("search by author!");
		author.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				authorMouseClicked(evt);
			}
		});

		date.setText("search by date!");
		date.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				dateMouseClicked(evt);
			}
		});

		key.setFont(new java.awt.Font("David", 1, 24)); // NOI18N
		key.setText("key:");

		jButton1.setText("Search");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jButton2.setText("Exite");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		to.setFont(new java.awt.Font("David", 1, 18)); // NOI18N
		to.setText("To");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(layout.createSequentialGroup()
										.addContainerGap()
										.addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGroup(layout.createSequentialGroup()
												.addGap(22, 22, 22)
												.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(layout.createSequentialGroup()
																.addComponent(key)
																.addGap(41, 41, 41))
																.addGroup(layout.createSequentialGroup()
																		.addComponent(to, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
																		.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
																		.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
																				.addComponent(jTextField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
																				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
																						.addComponent(jButton1)
																						.addGap(18, 18, 18)
																						.addComponent(jButton2)))
																						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
																						.addContainerGap(55, Short.MAX_VALUE))
																						.addGroup(layout.createSequentialGroup()
																								.addGap(91, 91, 91)
																								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																										.addComponent(date)
																										.addComponent(author, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addComponent(conetnt, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
																										.addContainerGap(208, Short.MAX_VALUE))
		);
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addContainerGap()
						.addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(conetnt)
						.addGap(18, 18, 18)
						.addComponent(author)
						.addGap(18, 18, 18)
						.addComponent(date)
						.addGap(18, 18, 18)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
								.addGroup(layout.createSequentialGroup()
										.addComponent(key, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
										.addGap(36, 36, 36))
										.addGroup(layout.createSequentialGroup()
												.addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
												.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(to, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
														.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
														.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
																.addComponent(jButton1)
																.addComponent(jButton2))
																.addGap(27, 27, 27))
		);

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
		// TODO add your handling code here:
		if (this.conetnt.isSelected()){
			try {
				Object [][] data=  this._CurEnter. displayMessage( this._curTUI.sendMessageAndWaitForReply("search content " + this.jTextField2.getText()));
				System.out.println(data.length+ "  my legnth");
				this._CurEnter. intialSearchMessag(data);
			} catch (IOException ex) {
				Logger.getLogger(Search.class.getName()).log(Level.SEVERE, null, ex);
			}
		}
		if (this.author.isSelected()){
			try {
				System.out.println("test Auter");
				Object [][] data=  this._CurEnter. displayMessage( this._curTUI.sendMessageAndWaitForReply("search author " + this.jTextField2.getText()));
				this._CurEnter. intialSearchMessag(data);
			} catch (IOException ex) {
				Logger.getLogger(Search.class.getName()).log(Level.SEVERE, null, ex);
			}
		}
		if (this.date.isSelected()){
			try {
				System.out.println("test Date");
				String fromDate=ParseDate(jTextField2.getText());
				String toDate=ParseDate(jTextField1.getText());
				System.out.println(fromDate);
				System.out.println(toDate);
				System.out.println("search date " + fromDate+" "+toDate);
				//truble
				System.out.println("MotiKing");

				System.out.println(this._curTUI.sendMessageAndWaitForReply("search date " + fromDate+" "+toDate));
				//truble
				System.out.println("MotiKing");

				Object [][] data=  this._CurEnter. displayMessage( this._curTUI.sendMessageAndWaitForReply("search date " + fromDate+" "+toDate));
				for (int i=0;i<data.length;i++){
					System.out.println(data[i][0]);
					System.out.println(data[i][1]);
					System.out.println(data[i][2]);
					System.out.println(data[i][3]);
				}
				this._CurEnter. intialSearchMessag(data);
			} catch (IOException ex) {
				Logger.getLogger(Search.class.getName()).log(Level.SEVERE, null, ex);
			}
		}

		this.hide();
	}//GEN-LAST:event_jButton1ActionPerformed

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
		// TODO add your handling code here:
		this.hide();
	}//GEN-LAST:event_jButton2ActionPerformed
	private String ParseDate(String da){
		String ans=null;
		String day=da.substring(0,da.indexOf("/"));
		da=da.substring(da.indexOf("/")+1,da.length());
		String Month=da.substring(0, da.indexOf("/"));
		String year=da.substring(da.indexOf("/")+1,da.length());
		ans=Month+"/"+day+"/"+year;
		return ans;
	}

	private void conetntMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_conetntMouseClicked
		// TODO add your handling code here:
		this.date.setSelected(false);
		this.author.setSelected(false);
		this.conetnt.setSelected(true);
		this.to.setVisible(false);
		this.key.setText("Key");
		this.jTextField1.setVisible(false);
	}//GEN-LAST:event_conetntMouseClicked

	private void authorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_authorMouseClicked
		// TODO add your handling code here:
		this.date.setSelected(false);
		this.author.setSelected(true);
		this.conetnt.setSelected(false);
		this.to.setVisible(false);
		this.key.setText("Key");
		this.jTextField1.setVisible(false);
	}//GEN-LAST:event_authorMouseClicked

	private void dateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dateMouseClicked
		// TODO add your handling code here:
		this.date.setSelected(true);
		this.author.setSelected(false);
		this.conetnt.setSelected(false);
		this.to.setVisible(true);
		this.key.setText("From");
		this.jTextField1.setVisible(true);
	}//GEN-LAST:event_dateMouseClicked

	private void conetntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conetntActionPerformed
		// TODO add your handling code here:
	}//GEN-LAST:event_conetntActionPerformed

	/**
	 * @param args the command line arguments
	 */


	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JCheckBox author;
	private javax.swing.JCheckBox conetnt;
	private javax.swing.JCheckBox date;
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JTextField jTextField1;
	private javax.swing.JTextField jTextField2;
	private javax.swing.JLabel key;
	private javax.swing.JLabel to;
	// End of variables declaration//GEN-END:variables

}
